### PR TITLE
#209 Fix grunt build_min not minifying

### LINKED ISSUE #209: Grunt webpack:prod task does not minify

### PR DESCRIPTION
**Pull request by ascendedguard**
When each require ran, `Object.assign()` ran, and it was overwriting the base configuration so settings were getting mixed up when executing. This was a little ridiculous to track down, and luckily I noticed flipping the order of dev/prod caused the files to get minified.

Resolves #209

### CODE REVIEW

File: Gruntfile.js [hunk 1]
```diff
@@ -75,7 +75,7 @@ module.exports = function (grunt) {
   });
 
   grunt.registerTask('build_dev', ['webpack:dev', 'ts:server', 'less', 'concat:js_dependencies']);
-  grunt.registerTask('build_min', [/*'webpack:prod', */'ts:server', 'less', 'concat:js_dependencies_min']);
+  grunt.registerTask('build_min', ['webpack:prod', 'ts:server', 'less', 'concat:js_dependencies_min']);
```
Comment (cynicaloptimist) [inline Gruntfile.js]: You can remove the `webpack` task from the `npm postinstall` script in `package.json`
